cargo-features = ["per-package-target", "edition2024"]

[package]
name = "ofvr"
version = "0.1.0"
edition = "2021"
autobins = false
autoexamples = false
autobenches = false
default-target = "aarch64-apple-darwin"
[package.metadata]
cargo-args = ["-Zmtime-on-use", "-Zavoid-dev-deps", "-Zcustom_mir"]
targets = [
    "aarch64-apple-darwin",
]

[dependencies]
base32 = "0.5.1"
# carbon14 = { path = "../../../../personal/carbon14" }
# chrono = { version = "0.4.38", features = ["serde", "libc"] }
# flate2 = "1.0.30"
# hex = "0.4.3"
# sanitation = { path = "../gadgets/packages/sanitation" }
# thread-group = { path = "../gadgets/packages/thread-group" }
# zstd = "0.13.1"
bincode = "1.3.3"
bzip2 = "0.4.4"
clap = { version = "4.5.4", features = ["derive", "wrap_help", "env", "unicode", "string", "cargo"] }
t16 = { path = "../t16" }
enum-to-string = { path = "../gadgets/packages/enum-to-string" }
flate2 = "1.0.34"
gzip = "0.1.2"
iocore = { path = "../gadgets/packages/iocore" }
otpauth = "0.5.1"
rand = "0.8.5"
rbac = "0.1.0"
rbac-macro = "0.1.0"
rsa = "0.9.6"
serde = { version = "1.0.210", features = ["derive"] }
ed25519 = { version = "2.2.3", features = ["serde", "pem", "pkcs8"] }
pkcs8 = { version = "0.10.2", features = ["des-insecure", "std", "pkcs5", "3des"] }
pkcs5 = { version = "0.7.1", features = ["des-insecure", "3des"] }
des = "0.8.1"
crypto-common = { version = "0.1.6", features = ["std", "rand_core"] }
security-framework = { version = "3.0.0", features = ["OSX_10_13", "log"] }

[[bin]]
name = "ofvr"
path = "ofvr.rs"
test = false
doctest = false

[lib]
name = "ofvr"
path = "ofvr/lib.rs"
test = true
doctest = false
bench = false
doc = false
plugin = false
harness = true
edition = "2021"
crate-type = ["lib"]
required-features = []

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(tarpaulin)'] }
