#!/usr/bin/env bash
set -e

export RUST_BACKTRACE=1


rm -f tests/cargo-run.ofvr

run() {
    echo -e "\033[1;38;5;220mofvr ${*}\033[0m"
    cargo build
    target/debug/ofvr $* #rust-lldb target/debug/ofvr -- $*
}
cargo check -q

run conf init -f "gabrielteratos@gmail.com" "Gabriel Falcão G DeMoura"
run conf get
cat >tests/cargo-run.txt <<EOF
# ofvr commit 1 @ $(date)
EOF
run commit -m 'test' tests/cargo-run.txt
sleep 1
cat >tests/cargo-run.txt <<EOF
# ofvr commit 2 @ $(date)
EOF

run commit -m 'test' tests/cargo-run.txt

run log tests/cargo-run.ofvr

cat >tests/cargo-run.txt <<EOF
# ofvr commit 3 @ $(date)
EOF

run diff tests/cargo-run.txt
